File submission on frontend to backend
eatcode-gt/eatcodeweb pull request #28
Opened 2022-11-17 01:34 UTC by aaronliuo

Rearranged the create form onSubmit function to submit problem data and test case files to the backend properly. There are three axios requests onSubmit now. First axios request essentially gets the last post id so it can assign the next problem's id. Second request sends the problem data. Third request sends the files.

2022-11-17 02:51 UTC, Giovanni1014 requested changes
unnecessary use of state

2022-11-17 02:51 UTC, Giovanni1014 commented on frontend/src/pages/create.js
> +  const [file, setFile] = useState(null);
I don't think we need file to be a state cuz we don't need it rendered every time it changes.

2022-11-17 03:20 UTC, aaronliuo commented on frontend/src/pages/create.js
> +  const [file, setFile] = useState(null);
Okay, Ill look into changing it

2022-11-17 20:26 UTC, Giovanni1014 approved these changes
Great work

2022-11-22 22:26 UTC, r4c3 approved these changes
approved by default pr30

2022-11-22 22:27 UTC, merged